# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Set Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
      
    - name: Run install
      uses: borales/actions-yarn@v5
      with:
        cmd: install # will run `yarn install` command
        
    - name: Generate
      uses: borales/actions-yarn@v5
      with:
        cmd: generate # will run `yarn install` command
        
    - name: List files
      run: ls built/public
      
    - name: Remove remote files
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: cd app/sites/landing/dist && rm -rf *
        
    - name: Copy generated files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: built/public/*
        target: app/sites/landing/dist
        strip_components: 2

